[project]
name = "gradr-mcp"
version = "0.1.0"
description = "MCP Server for GradrAI"
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.21.2",
]
